<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->partial(__DIR__ .'/../../views/layouts/header.phtml'); ?>
  </head>
  <body  class="wrapper"> 
    <?php $this->yieldView(); ?>
  </body>
  <?php $this->partial(__DIR__ .'/../../views/layouts/footer.phtml'); ?>
</html>

